#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom anonymizer anonymize
#' @importFrom broom tidy
#' @importFrom cli cli_abort
#' @importFrom cli qty
#' @importFrom data.table :=
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr group_modify
#' @importFrom dplyr left_join
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr recode
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr transmute
#' @importFrom dplyr ungroup
#' @importFrom exactRankTests wilcox.exact.formula
#' @importFrom glue glue
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx createStyle
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom openxlsx setColWidths
#' @importFrom openxlsx setRowHeights
#' @importFrom openxlsx writeData
#' @importFrom pbapply pblapply
#' @importFrom raster cv
#' @importFrom readr read_csv
#' @importFrom readr write_csv
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @importFrom rlang is_empty
#' @importFrom rlang sym
#' @importFrom stats setNames
#' @importFrom stats shapiro.test
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_sub
#' @importFrom stringr str_subset
#' @importFrom stringr str_which
#' @importFrom tibble as_tibble
#' @importFrom tidyr expand_grid
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr separate
#' @importFrom tidyr unite
#' @importFrom tidyselect all_of
#' @importFrom tidyselect any_of
#' @importFrom usethis use_data
#' @importFrom usethis use_data_raw
#' @importFrom utils combn
#' @importFrom utils data
## usethis namespace: end
NULL
